// UNICODE Support Set Definitions
//
// File:	unicode_data_support_sets.h

// Generated by make_unicode_data.cc

// See unicode_data.h for documentation.


enum {

    ascii            = ( 1 << 16 ),
    latin1           = ( 1 << 17 )

};
